name: evil-workflow
on: workflow_dispatch

jobs:
  evil-job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      with:
        fetch-depth: 0 # Checkout everything to get access to the tags
        ref: ${{github.event.pull_request.head.ref}}
        repository: ${{github.event.pull_request.head.repo.full_name}}
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: open evil PR
      run: |
        gh pr create --title="evil test PR" --body "evil test body" --base develop --head semgrep:yosef/auto-version-bump
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
